// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InventoryManagementDB.Data.InventoryManagement
{
    public partial class Inventory
    {
        public int Id { get; set; }
        public string Object { get; set; }
        public string Location { get; set; }
        public int? Amount { get; set; }
        public string Comment { get; set; }
        public DateTime? Date {get;set;}
        public string UserName { get; set; }
    }
}
